/**
 * One-off extractor for Node-RED function nodes inside the Guadalupe flow
 * backup. Re-run when the .json is replaced/refreshed.
 *
 *   node _extract.js
 *
 * Reads ../bkp-all-flows-obramax-guadalupe-*.json (most recent), writes one
 * .js per function node alongside this script. Also (re)generates
 * `_inventory.md` with the full list grouped by tab/group.
 */

const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const GUADALUPE = path.dirname(HERE);

// pick the most recent backup file
const backups = fs.readdirSync(GUADALUPE)
  .filter((f) => /^bkp-all-flows-obramax-guadalupe-.*\.json$/i.test(f))
  .sort()
  .reverse();

if (backups.length === 0) {
  console.error('No backup .json found in', GUADALUPE);
  process.exit(1);
}

const backupPath = path.join(GUADALUPE, backups[0]);
console.log('Reading', backupPath);

const flows = JSON.parse(fs.readFileSync(backupPath, 'utf8'));

const tabs = Object.fromEntries(
  flows.filter((n) => n.type === 'tab').map((n) => [n.id, n.label || '(unnamed-tab)'])
);
const groups = Object.fromEntries(
  flows.filter((n) => n.type === 'group').map((n) => [n.id, n.name || '(unnamed-group)'])
);

const slug = (s) =>
  (s || 'unnamed')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'unnamed';

const shortId = (id) => id.replace(/[^a-z0-9]/gi, '').slice(-6);

const functions = flows.filter((n) => n.type === 'function');

// clean existing extracted .js (keep _extract.js + _inventory.md)
for (const f of fs.readdirSync(HERE)) {
  if (f.endsWith('.js') && f !== '_extract.js') {
    fs.unlinkSync(path.join(HERE, f));
  }
}

const rows = [];
for (const node of functions) {
  const name = node.name || '';
  const tab = tabs[node.z] || node.z;
  const group = groups[node.g] || '';
  const file = `${slug(name)}--${shortId(node.id)}.js`;

  const header =
    `/**\n` +
    ` * Node-RED function — exported from Guadalupe flow backup.\n` +
    ` *   tab:     ${tab}\n` +
    ` *   group:   ${group || '(none)'}\n` +
    ` *   name:    ${name || '(unnamed)'}\n` +
    ` *   node id: ${node.id}\n` +
    ` *\n` +
    ` * Source: ${path.basename(backupPath)}\n` +
    ` * Generated by _extract.js — do not edit by hand; round-trip through\n` +
    ` * Node-RED + re-export the flow if you need to change the function.\n` +
    ` */\n\n`;

  fs.writeFileSync(path.join(HERE, file), header + (node.func || '') + '\n', 'utf8');

  rows.push({ name: name || '(unnamed)', tab, group: group || '(none)', file, id: node.id });
}

// build inventory grouped by tab → group → name
const inv = {};
for (const r of rows) {
  ((inv[r.tab] ||= {})[r.group] ||= []).push(r);
}

const lines = [
  '# Functions inventory — Guadalupe',
  '',
  `Auto-generated by \`_extract.js\` from \`${path.basename(backupPath)}\`.`,
  `Total: **${rows.length} function nodes**.`,
  '',
];
for (const [tab, gs] of Object.entries(inv)) {
  lines.push(`## Tab: \`${tab}\``);
  lines.push('');
  for (const [g, items] of Object.entries(gs)) {
    lines.push(`### Group: \`${g}\``);
    lines.push('');
    lines.push('| Name | Node id | File |');
    lines.push('| ---- | ------- | ---- |');
    for (const r of items) {
      lines.push(`| ${r.name} | \`${r.id}\` | [\`${r.file}\`](./${r.file}) |`);
    }
    lines.push('');
  }
}
fs.writeFileSync(path.join(HERE, '_inventory.md'), lines.join('\n'), 'utf8');

console.log(`Wrote ${rows.length} function files + _inventory.md to ${HERE}`);
