/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     Monitoramento
 *   group:   Central Monitor
 *   name:    (unnamed)
 *   node id: 351f13dc.dfcf1c
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

let healthcheckFailureCount = flow.get('healthcheck_failure_count');

if (healthcheckFailureCount == null) {
    healthcheckFailureCount = 0;
}

healthcheckFailureCount += 1;

flow.set('healthcheck_failure_count', healthcheckFailureCount);

return msg;
