/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Send logs every 1 minute
 *   name:    (unnamed)
 *   node id: 1271d15f.17706f
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const now = new Date();

now.setMinutes(now.getMinutes() - 1);

msg.payload = {
    dateStart: now.toISOString()
};

return msg;
