/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Status da Automação
 *   name:    (unnamed)
 *   node id: 4c65c5d9.8a334c
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

let automationOn = global.get('AutoOn');

if (automationOn == null) {
    automationOn = true;
}

msg.payload = {
    'Automação': [{
        ts: new Date().getTime(),
        values: {
            status: automationOn
        }
    }]
}

return msg;
