/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   (none)
 *   name:    (unnamed)
 *   node id: 5c8b612c.39b58
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const devices = flow.get('devices'); 
const centralId = env.get('CENTRAL_UUID');

const messages = [];

Object.keys(devices).forEach((key) => {
    const device = devices[key]; 

    const message = {
        payload: {
            device: {
                centralId: centralId
            }
        }
    };

    messages.push(message);
});

msg.payload = messages;

return msg;
