/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   (unnamed-group)
 *   name:    (unnamed)
 *   node id: 8fce55f9.821338
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const slaveIds = msg.req.params.slaveIds;

msg.payload = slaveIds.split(",");
return msg;
