/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Modbus
 *   name:    (unnamed)
 *   node id: 13de74fa.11073b
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const convertFLOAT32 = (registers) => {
  // Combine the registers to get the 32-bit integer representation
  // Assuming big-endian format
  const combined = (registers[0] << 16) | registers[1];

  // Create a buffer and a DataView for conversion
  const buffer = new ArrayBuffer(4); // 4 bytes = 32 bits
  const view = new DataView(buffer);

  // Store the combined integer in the DataView as a 32-bit integer
  // Adjust this based on the actual endianness
  view.setUint32(0, combined, false); // 'false' for big-endian, 'true' for little-endian

  // Now read the value back as a float
  const floatValue = view.getFloat32(0, false); // Match the endianness

  return floatValue;
};


const a = msg.payload[0];
const b = msg.payload[1];


let bufferA = Buffer.alloc(2);
let bufferB = Buffer.alloc(2);

bufferA.writeUint16BE(a, 0);
bufferB.writeUint16BE(b, 0);

bufferA = bufferA.reverse();
bufferB = bufferB.reverse();

let newA = bufferA.readUint16BE(0);
let newB = bufferB.readUint16BE(0);

const converted2 = convertFLOAT32([newB, newA]);

msg.payload = converted2;

return msg;
