/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   (unnamed-group)
 *   name:    (unnamed)
 *   node id: 83b8be49.9bbfc
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const nameParam = msg.req.params.name;
const nameArray = nameParam.split(",");
const ids = [];

const devicesObj = flow.get('devices') || {};
const devicesArray = Object.values(devicesObj); 
node.warn("deviceArray", devicesArray);

nameArray.forEach(data => {
    const device = devicesArray.find(device => 
        device.name && device.name.indexOf(data) > -1 
    );
    node.warn(device);
    
    if (device && device.slaveId !== undefined) { 
        ids.push(device.slaveId);
    } else {
        node.warn("Dispositivo não encontrado para: " + data);
    }
});
msg.payload = ids.join(",");
return msg;
