/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   (unnamed-group)
 *   name:    (unnamed)
 *   node id: 6a7b8b02.55a3b4
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const devices = msg.payload;

const processedDevices = devices.map(device => {
  const multiplierMatch = device.device_name.match(/x(\d+)/);
  const multiplier = multiplierMatch ? parseInt(multiplierMatch[1], 10) : 1;

  const cleanedName = device.device_name
    .replace(/^Hidr\.\s*/, '') 
    .replace(/\s*x\d+.*$/, ''); 

  const totalConsumptionL = parseFloat(device.total_consumption_l) * multiplier;
  const maxHourlyConsumptionL = parseFloat(device.max_hourly_consumption_l) * multiplier;
  const minHourlyConsumptionL = parseFloat(device.min_hourly_consumption_l) * multiplier;
  const avgLPerHour = parseFloat(device.avg_l_per_hour) * multiplier;

  return {
    ...device, 
    device_name: cleanedName, 
    total_consumption_l: totalConsumptionL.toString(),
    max_hourly_consumption_l: maxHourlyConsumptionL.toString(),
    min_hourly_consumption_l: minHourlyConsumptionL.toString(),
    avg_l_per_hour: avgLPerHour.toString()
  };
});

msg.payload = processedDevices;
return msg;
