/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Send logs every 1 minute
 *   name:    (unnamed)
 *   node id: a92ec69f.0427f8
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const commandIds = msg.payload.reduce((acc, button) => {
    acc[button.rfir_command_id] = {
        name: button.name,
        remoteName: button.rfir_remote_name.split(' - ')[1],
    }

    return acc;
}, {});

msg.payload = commandIds;

flow.set('rfirCommands', commandIds)

return msg;
