/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Estouro Demanda
 *   name:    (unnamed)
 *   node id: 5bf6728a.0e70b4
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const devices = flow.get('devices') || {};
const ignoreList = flow.get('ignore_schedules_list') || {};

const newDeviceName = 'SPT11: COMP1';

const flowDevice = devices[newDeviceName];

node.warn({
    msg: 'Flow device: ',
    device: flowDevice,
});

msg.automation = msg.payload;
msg.flowDevice = newDeviceName;

msg.payload = {
    generic: true,
    id: flowDevice.slaveId,
    channel: flowDevice.channelId,
    value: flowDevice.deviceKind === 'inverted_actionable' ? 100 : 0, // turn off
};


ignoreList[newDeviceName] = true;

flow.set('ignore_schedules_list', ignoreList);

return msg;
