/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Save Schedule from Thingsboard
 *   name:    (unnamed)
 *   node id: 250e6ec2.cde122
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

msg.payload = `Restored ${msg.payload.length} holidays.`;

return msg;
