/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Modbus
 *   name:    (unnamed)
 *   node id: 215e4d11.63bc72
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

let currIndex = this.currIndex || 0;
let lastTrafoPowerRead = this.lastTrafoPowerRead || 0;

const attributes = [{
    "startAddress": 16,
    "count": 2,
    "attributeName": "Tensão A",
    "helexiaName": "voltage_a",
}, {
    "startAddress": 18,
    "count": 2,
    "attributeName": "Tensão B",
    "helexiaName": "voltage_b",
}, {
    "startAddress": 20,
    "count": 2,
    "attributeName": "Tensão C",
    "helexiaName": "voltage_c",
}, {
    "startAddress": 22,
    "count": 2,
    "attributeName": "Corrente A",
    "helexiaName": "current_a",
}, {
    "startAddress": 24,
    "count": 2,
    "attributeName": "Corrente B",
    "helexiaName": "current_b",
}, {
    "startAddress": 26,
    "count": 2,
    "attributeName": "Corrente C",
    "helexiaName": "current_c",
}, {
    "startAddress": 28,
    "count": 2,
    "attributeName": "Potencia Ativa A",
    "helexiaName": "power_a",
}, {
    "startAddress": 30,
    "count": 2,
    "attributeName": "Potencia Ativa B",
    "helexiaName": "power_b",
}, {
    "startAddress": 32,
    "count": 2,
    "attributeName": "Potencia Ativa C",
    "helexiaName": "power_c",
}, {
    "startAddress": 12,
    "count": 2,
    "attributeName": "Potencia Ativa Trifásica",
    "helexiaName": "power",
}, {
    "startAddress": 10,
    "count": 2,
    "attributeName": "Potencia Reativa Trifásica",
    "helexiaName": "power_reactive",
}, {
    "startAddress": 34,
    "count": 2,
    "attributeName": "Potencia Reativa A",
    "helexiaName": "power_reactive_a",
}, {
    "startAddress": 36,
    "count": 2,
    "attributeName": "Potencia Reativa B",
    "helexiaName": "power_reactive_b",
}, {
    "startAddress": 38,
    "count": 2,
    "attributeName": "Potencia Reativa C",
    "helexiaName": "power_reactive_c",
}, {
    "startAddress": 6,
    "count": 2,
    "attributeName": "Fator de Potência Trifásico",
    "helexiaName": "fp",
}, {
    "startAddress": 46,
    "count": 2,
    "attributeName": "Fator de Potência A",
    "helexiaName": "fp_a",
}, {
    "startAddress": 48,
    "count": 2,
    "attributeName": "Fator de Potência B",
    "helexiaName": "fp_b",
}, {
    "startAddress": 50,
    "count": 2,
    "attributeName": "Fator de Potência C",
    "helexiaName": "fp_c",
}, {
    "startAddress": 52,
    "count": 2,
    "attributeName": "Energia Ativa Positiva",
    "helexiaName": "kWh",
}, {
    "startAddress": 54,
    "count": 2,
    "attributeName": "Energia Reativa Positiva",
    "helexiaName": "KVArh",
}];

const devices = {
    9: 'Trafo',
    11: 'QFAC 1',
    12: 'QFAC QGBT',
    13: 'QFAC VBF',
    14: 'QFAC Portaria',
    17: 'QFAC 2',
    18: 'QFAC 1B',
};

let allDevices = [];

for (const key in devices) {
    for (let a = 0; a < attributes.length; a++) {
        allDevices.push({
            ...attributes[a],
            deviceName: devices[key],
            address: parseInt(key),
        });
    }
}

const now = Date.now();
const trafoPowerAttribute = allDevices.find(attr => 
    attr.deviceName === 'Trafo' && 
    attr.attributeName === 'Potencia Ativa Trifásica'
);
let currAttribute;

// Check if it's been more than 60 seconds since the last Trafo power read
if (trafoPowerAttribute && (now - lastTrafoPowerRead) > 60000) {
    node.warn('Prioritizing trafo!!');
    currAttribute = trafoPowerAttribute;
    this.lastTrafoPowerRead = now;
} else {
    if (currIndex >= (allDevices.length - 1)) {
        currIndex = 0;
    } else {
        currIndex += 1;
    }
    currAttribute = allDevices[currIndex];
    this.currIndex = currIndex;
}

msg.currIndex = currIndex;
msg.numAttributes = allDevices.length;
msg.payload = {
    ...currAttribute,
    type: 'none',
    readType: 'input',
};

msg.topic = currAttribute.attributeName;
msg.helexiaTopic = currAttribute.helexiaName;
msg.deviceName = currAttribute.deviceName;

return msg;
