/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   API Export Water
 *   name:    (unnamed)
 *   node id: 6e8798ee.4ff678
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

function formatForPostgresInQuery(arrayOfArrays) {
    const formattedItems = arrayOfArrays.map(subArray => 
        `(${subArray.join(', ')})`
    );
    return `(${formattedItems.join(', ')})`;
}

const devices = flow.get('devices') || {};

const flowDevices = [];

for (const devKey in devices) {
    const device = devices[devKey];
    if (device.type === 'flow_sensor') {
        flowDevices.push([device.slaveId, device.channelId]);
    }
}

if (flowDevices.length === 0) {
    return null;
}

msg.payload = {
    devices: formatForPostgresInQuery(flowDevices),
};

return msg;
