/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Send logs every 1 minute
 *   name:    (unnamed)
 *   node id: 11e8858e.6149ca
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const log = msg.payload;
const time = log.timestamp;
const slave = msg.slave;
const commandIds = flow.get('rfirCommands');

if (!time) {
    return null;
}

const ts = new Date(time).getTime();

// This is a slave device:
if (log.channel != null && slave.channels_list && slave.channels_list.length > 0) {
    const foundDevice = slave.channels_list.find((channel) => {
        return channel.channel === log.channel;
    });
    
    if (foundDevice) {
        const device = foundDevice.name;
        return {
            payload: {
                [device]: [{
                    ts,
                    values: {
                        log: {
                            ...log,
                            device
                        },
                    },
                }]
            }
        }
    }
    // TODO: send on output 2 so we can error
}
// This is a IR remote:
if (log.rfir_command_id != null && slave.devices && slave.devices.length > 0) {
    let command = null;

    const allCommands = slave.devices.reduce((acc, dev) => {
        acc = [...acc, ...dev.rfir_commands];
        
        return acc;
    }, []);
    const foundCommand = allCommands.find((command) => {
       return command.id === log.rfir_command_id; 
    });
    if (foundCommand) {
        if (commandIds.hasOwnProperty(foundCommand.id)) {
            const commandName = commandIds[foundCommand.id];
            const command = commandIds[foundCommand.id];
            
            if (!command) return null;

            return {
                payload: {
                    [command.remoteName]: [{
                        ts,
                        values: {
                            log: {
                                ...log,
                                command: command.name,
                            }
                        },
                    }]
                }
            }
        }
    }
    
    // TODO: send on output 2 so we can error
}

return null;
