/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Demand -> Control device
 *   name:    (unnamed)
 *   node id: 3e7cc317.b0dfcc
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const vetordevice = global.get('deviceatual') || [] ;

let buba=
{
    id:msg.payload.id,
    canal: msg.payload.value
}
for(let x=0 ; x < vetordevice.length; x++)
{
    if(vetordevice[x].id == msg.payload.id )
    {
        if(vetordevice[x].channels[msg.payload.channel].output == msg.payload.value)
        {
           msg.payload=1;
            return null;
        }
    }
}
return msg;
