/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Status da Automação
 *   name:    (unnamed)
 *   node id: 71d2c9e6.c844c8
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const autoOn = msg.payload.automationStatus;

global.set('AutoOn', autoOn);

msg.payload = `${autoOn}`;

return msg;
