/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   Store devices to flow.devices
 *   name:    (unnamed)
 *   node id: 71e91e26.89bd3
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */


return msg;
