/**
 * Node-RED function — exported from Guadalupe flow backup.
 *   tab:     MQTT
 *   group:   MQTT
 *   name:    Wh
 *   node id: 5845b50a.aea33c
 *
 * Source: bkp-all-flows-obramax-guadalupe-2026-05-12-11-39.json
 * Generated by _extract.js — do not edit by hand; round-trip through
 * Node-RED + re-export the flow if you need to change the function.
 */

const slaveName = Object.keys(msg.payload)[0];
const keyName = 'last_consumption_' + slaveName.replace(/ /gi, '_');

function calculateWh(lastMsg, msg) {
  const delta = (msg.ts - lastMsg.ts) / 3600 / 1000;

  const Wh = msg.consumption * delta;

  return Wh;
}

let currentConsumption = {
    ts: new Date().getTime(),
    consumption: (msg.payload[slaveName][0].consumption || 0).toFixed(2),
};

const lastConsumptionRead = flow.get(keyName);

if (lastConsumptionRead) {
    const Wh = (calculateWh(lastConsumptionRead, currentConsumption) || 0).toFixed(2);

    msg.payload = {
        [slaveName]: [{
            ts: new Date().getTime(),
            values: {
                ...msg.payload[slaveName][0],
                Wh
            }
        }]
    };
}

flow.set(keyName, currentConsumption);

return msg;
