[
  {
    id: 9,
    type: 'three_phase_sensor',
    addr_low: 50,
    addr_high: 248,
    name: '3F ViverParque N_134/135/155/156/157(AL1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [
      {
        id: 1,
        type: 'lamp',
        channel: 0,
        name: 'ignorar',
        config: null,
        scene_up_id: null,
        scene_down_id: null,
        value: 0,
        input: 0,
        output: 0,
      },
    ],
    status: 'offline',
  },
  {
    id: 26,
    type: 'outlet',
    addr_low: 200,
    addr_high: 249,
    name: 'MQTT Sync',
    code: '002-002-002-012',
    clamp_type: null,
    config: { source: 'mqttSyncStatus', virtual: true, mqttSyncStatus: 'disable' },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [
      {
        id: 2,
        type: 'plug',
        channel: 0,
        name: 'MQTT Sync',
        config: { confirm: false },
        scene_up_id: null,
        scene_down_id: null,
        value: 0,
        input: 0,
        output: 0,
      },
    ],
    status: 'offline',
  },
  {
    id: 20,
    type: 'outlet',
    addr_low: 112,
    addr_high: 249,
    name: 'Sw Reboot L1 Ilha Plaza',
    code: '002-002-002-012',
    clamp_type: null,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'offline',
  },
  {
    id: 25,
    type: 'outlet',
    addr_low: 244,
    addr_high: 249,
    name: 'Sw Reborn AL1',
    code: '002-002-002-012',
    clamp_type: null,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'offline',
  },
  {
    id: 11,
    type: 'three_phase_sensor',
    addr_low: 254,
    addr_high: 248,
    name: '3F CasaeVideo N_133A/B/C/D/E(AL1)',
    code: '002-002-002-015',
    clamp_type: 2,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 17533,
    channels: [],
    status: 'online',
  },
  {
    id: 17,
    type: 'three_phase_sensor',
    addr_low: 129,
    addr_high: 248,
    name: '3F semLoja N_136(AL2)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 1229,
    channels: [],
    status: 'online',
  },
  {
    id: 12,
    type: 'three_phase_sensor',
    addr_low: 56,
    addr_high: 248,
    name: '3F EstiloNatural N_151(AL2)',
    code: '003-003-003-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 354,
    channels: [],
    status: 'online',
  },
  {
    id: 10,
    type: 'three_phase_sensor',
    addr_low: 115,
    addr_high: 248,
    name: '3F  FastandFurious N_154(AL1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: { config_clamp: { confirmed: true, value: 0 } },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'online',
  },
  {
    id: 18,
    type: 'three_phase_sensor',
    addr_low: 197,
    addr_high: 249,
    name: '3F Drogasmil N_115/116/117(AL2)',
    code: '003-003-003-015',
    clamp_type: 1,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 5353,
    channels: [],
    status: 'online',
  },
  {
    id: 2,
    type: 'three_phase_sensor',
    addr_low: 107,
    addr_high: 248,
    name: '3F Vialaser N_137',
    code: '002-002-002-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'online',
  },
  {
    id: 15,
    type: 'three_phase_sensor',
    addr_low: 87,
    addr_high: 248,
    name: '3F CaliforniaCoffee N_147(AL1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: { config_clamp: { confirmed: true, value: 0 } },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 2652,
    channels: [],
    status: 'online',
  },
  {
    id: 13,
    type: 'three_phase_sensor',
    addr_low: 46,
    addr_high: 248,
    name: '3F Conserte N_152(Al2)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 658,
    channels: [],
    status: 'online',
  },
  {
    id: 5,
    type: 'three_phase_sensor',
    addr_low: 104,
    addr_high: 249,
    name: '3F Ortobom N_107/108/109(AL1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'online',
  },
  {
    id: 19,
    type: 'three_phase_sensor',
    addr_low: 24,
    addr_high: 249,
    name: '3F SantaCor N_101(AL1)',
    code: '003-003-003-015',
    clamp_type: 0,
    config: { tolerance: 0, min_variance: 5 },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 590,
    channels: [],
    status: 'online',
  },
  {
    id: 24,
    type: 'outlet',
    addr_low: 116,
    addr_high: 249,
    name: 'Reboot L3',
    code: '002-002-002-012',
    clamp_type: null,
    config: {
      channelConfig: {
        channel0: { slaveId: 24, channel: 0, channel_type: 'REMOTE_INPUT', pulses: 1, output: 'HOLDING' },
        channel1: { slaveId: 24, channel: 1, channel_type: 'REMOTE_INPUT', pulses: 1, output: 'HOLDING' },
      },
    },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'offline',
  },
  {
    id: 8,
    type: 'three_phase_sensor',
    addr_low: 14,
    addr_high: 249,
    name: '3F Portuguesa N_102/103/104(AL1)',
    code: '003-003-003-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'online',
  },
  {
    id: 6,
    type: 'three_phase_sensor',
    addr_low: 102,
    addr_high: 248,
    name: '3F PetBoutique N_105/106(AL1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: { config_clamp: { confirmed: true, value: 0 } },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 6357,
    channels: [],
    status: 'online',
  },
  {
    id: 16,
    type: 'three_phase_sensor',
    addr_low: 215,
    addr_high: 249,
    name: '3F ÓticasCarol N_114(AL2)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 2053,
    channels: [],
    status: 'online',
  },
  {
    id: 4,
    type: 'three_phase_sensor',
    addr_low: 67,
    addr_high: 249,
    name: '3F Light N_135(AL1)',
    code: '003-003-003-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 1223,
    channels: [],
    status: 'online',
  },
  {
    id: 23,
    type: 'outlet',
    addr_low: 226,
    addr_high: 248,
    name: 'reboot L1 L2 ',
    code: '002-002-002-012',
    clamp_type: null,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'offline',
  },
  {
    id: 1,
    type: 'three_phase_sensor',
    addr_low: 35,
    addr_high: 248,
    name: '3F 4cantos N_138',
    code: '003-003-003-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 747,
    channels: [],
    status: 'online',
  },
  {
    id: 22,
    type: 'outlet',
    addr_low: 61,
    addr_high: 249,
    name: 'Reboot L2 Ilha Plaza',
    code: '002-002-002-012',
    clamp_type: null,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'offline',
  },
  {
    id: 3,
    type: 'three_phase_sensor',
    addr_low: 133,
    addr_high: 248,
    name: '3F DomettEstudoEstetica N111(al1)',
    code: '003-003-003-015',
    clamp_type: 0,
    config: null,
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'online',
  },
  {
    id: 14,
    type: 'three_phase_sensor',
    addr_low: 178,
    addr_high: 248,
    name: '3F LizFestaa N_121/122/123/124/125/126/127(AL1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: { config_clamp: { confirmed: true, value: 0 } },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 0,
    channels: [],
    status: 'online',
  },
  {
    id: 7,
    type: 'three_phase_sensor',
    addr_low: 88,
    addr_high: 248,
    name: '3F Don HelioN_104(al1)',
    code: '002-002-002-015',
    clamp_type: 0,
    config: { tolerance: 0, min_variance: 5, config_clamp: { confirmed: true, value: 0 } },
    temperature_correction: null,
    aggregate: true,
    version: '6.0.0',
    last_consumption: 1117,
    channels: [],
    status: 'online',
  },
];
