/**
 * Device naming utilities.
 *
 * Ported from data-ingestion-prod
 * (`packages/presetup-nextjs/src/lib/naming-rules.ts`), keeping the same
 * Mercosul plate semantics so device names generated by either codebase are
 * compatible.
 *
 * @module device
 */

// Exclude visually ambiguous glyphs from generated plates:
//   letters: no 'I' (confunde com 1) nem 'O' (confunde com 0)
//   digits:  no '0' (confunde com O) nem '1' (confunde com I)
const LETTERS = 'ABCDEFGHJKLMNPQRSTUVWXYZ'; // sem I, O
const DIGITS = '23456789'; // sem 0, 1

function randLetter(): string {
  return LETTERS[Math.floor(Math.random() * LETTERS.length)];
}

function randDigit(): string {
  return DIGITS[Math.floor(Math.random() * DIGITS.length)];
}

/**
 * Generates a random Mercosul-format plate string: `LLL D L DD`
 * (3 letters, 1 digit, 1 letter, 2 digits → 7 chars, e.g. `ABC1D23`).
 *
 * Visually ambiguous characters are excluded (letters omit `I`/`O`; digits
 * omit `0`/`1`), so the combination space is 24³ × 8 × 24 × 8² ≈ 4.5B.
 *
 * Each call returns one random sample — callers needing uniqueness against an
 * existing name set should retry until the result is not already taken.
 *
 * @returns a 7-character Mercosul plate string
 */
export function generateMercosulPlate(): string {
  return `${randLetter()}${randLetter()}${randLetter()}${randDigit()}${randLetter()}${randDigit()}${randDigit()}`;
}

// ─── Device-type name prefixes ───────────────────────────────────────────────

/** Fallback prefix used when a device type has no registered prefix. */
export const DEFAULT_DEVICE_TYPE_PREFIX = 'DEV.';

/**
 * Canonical map from device-type identifier to the name prefix prepended to a
 * generated device name (e.g. `3F COMP. ABC1D23`).
 *
 * Single source of truth, mirrored from
 * `data-ingestion-prod/packages/presetup-nextjs/src/lib/naming-rules.ts`
 * (`TYPE_PREFIX_MAP`). The `SW_*` board family (RFC-0003) is kept in sync with
 * that project's `structure-builder.ts`.
 */
export const DEVICE_TYPE_PREFIX_MAP: Record<string, string> = {
  COMPRESSOR: '3F COMP.',
  VENTILADOR: '3F VENT.',
  SELETOR_AUTO_MANUAL: 'S_AUTO_MANUAL.',
  TERMOSTATO: 'TEMP.',
  '3F_MEDIDOR': '3F',
  MOTOR: '3F MOTR.',
  ESCADA_ROLANTE: '3F ESRL.',
  ELEVADOR: '3F ELEV.',
  HIDROMETRO: 'HIDR.',
  SOLENOIDE: 'ABFE.',
  CONTROLE_REMOTO: 'AC',
  CAIXA_D_AGUA: 'SCD',
  CONTROLE_AUTOMACAO: 'GW_AUTO.',
  // RFC-0003 — SW_* board family (keep in sync with structure-builder.ts).
  SW_ILUMINACAO: 'ILUM.',
  SW_COMPRESSOR: 'COMP.',
  SW_GERADOR: 'GER.',
  SW_REDE: 'REDE',
};

/**
 * Returns the registered name prefix for a device type, or
 * `DEFAULT_DEVICE_TYPE_PREFIX` (`'DEV.'`) when the type is unknown/empty.
 *
 * Lookup is exact (keys are uppercase identifiers); pass the device's
 * canonical `type`/`deviceType` string.
 */
export function getDeviceTypePrefix(deviceType?: string | null): string {
  return DEVICE_TYPE_PREFIX_MAP[deviceType || ''] || DEFAULT_DEVICE_TYPE_PREFIX;
}

// ─── Device code (RFC-0206, Phase 3) ─────────────────────────────────────────

/** Fallback type token used when a device type is unknown/empty. */
export const DEFAULT_DEVICE_TYPE_TOKEN = 'DEV';

/**
 * Short uppercase tokens embedded in a device code, distinct from the human
 * name prefixes in {@link DEVICE_TYPE_PREFIX_MAP}. Only types whose desired code
 * token differs from the sanitized identifier need an entry here (e.g.
 * `3F_MEDIDOR` -> `3F`). Unmapped types fall back to a sanitized uppercase form.
 *
 * NOTE: the canonical short-token taxonomy is RFC-0206 Phase 3's open question;
 * this map is the explicit-override layer and is expected to grow as the device
 * taxonomy is reconciled with `DEVICE_TYPE_CONFIG`.
 */
export const DEVICE_TYPE_CODE_TOKEN: Record<string, string> = {
  '3F_MEDIDOR': '3F',
};

/**
 * Normalizes a device type into a short, uppercase, hyphen-safe token used in a
 * device code, e.g. `'3F_MEDIDOR'` -> `'3F'`, `'SW_ILUMINACAO'` -> `'SW-ILUMINACAO'`.
 *
 * Resolution order:
 *  1. exact override in {@link DEVICE_TYPE_CODE_TOKEN};
 *  2. otherwise the uppercased type with non-alphanumerics collapsed to `-`;
 *  3. {@link DEFAULT_DEVICE_TYPE_TOKEN} (`'DEV'`) for unknown/empty input.
 */
export function deviceTypeToken(deviceType?: string | null): string {
  const raw = String(deviceType || '').trim().toUpperCase();
  if (!raw) return DEFAULT_DEVICE_TYPE_TOKEN;
  if (DEVICE_TYPE_CODE_TOKEN[raw]) return DEVICE_TYPE_CODE_TOKEN[raw];
  const sanitized = raw.replace(/[^A-Z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return sanitized || DEFAULT_DEVICE_TYPE_TOKEN;
}

/**
 * Generates an opaque device code embedding the type token:
 * `D-<TYPE>-<plate>-<plate>`, e.g. `generateDeviceCode('3F_MEDIDOR')` ->
 * `'D-3F-XDN5R48-JQE6K43'`. Each `<plate>` is a 7-char Mercosul plate.
 */
export function generateDeviceCode(deviceType?: string | null): string {
  return `D-${deviceTypeToken(deviceType)}-${generateMercosulPlate()}-${generateMercosulPlate()}`;
}
