/**
 * Device naming utilities.
 *
 * Ported from data-ingestion-prod
 * (`packages/presetup-nextjs/src/lib/naming-rules.ts`), keeping the same
 * Mercosul plate semantics so device names generated by either codebase are
 * compatible.
 *
 * @module device
 */

// Exclude visually ambiguous glyphs from generated plates:
//   letters: no 'I' (confunde com 1) nem 'O' (confunde com 0)
//   digits:  no '0' (confunde com O) nem '1' (confunde com I)
const LETTERS = 'ABCDEFGHJKLMNPQRSTUVWXYZ'; // sem I, O
const DIGITS = '23456789'; // sem 0, 1

function randLetter(): string {
  return LETTERS[Math.floor(Math.random() * LETTERS.length)];
}

function randDigit(): string {
  return DIGITS[Math.floor(Math.random() * DIGITS.length)];
}

/**
 * Generates a random Mercosul-format plate string: `LLL D L DD`
 * (3 letters, 1 digit, 1 letter, 2 digits → 7 chars, e.g. `ABC1D23`).
 *
 * Visually ambiguous characters are excluded (letters omit `I`/`O`; digits
 * omit `0`/`1`), so the combination space is 24³ × 8 × 24 × 8² ≈ 4.5B.
 *
 * Each call returns one random sample — callers needing uniqueness against an
 * existing name set should retry until the result is not already taken.
 *
 * @returns a 7-character Mercosul plate string
 */
export function generateMercosulPlate(): string {
  return `${randLetter()}${randLetter()}${randLetter()}${randDigit()}${randLetter()}${randDigit()}${randDigit()}`;
}

// ─── Device-type name prefixes ───────────────────────────────────────────────

/** Fallback prefix used when a device type has no registered prefix. */
export const DEFAULT_DEVICE_TYPE_PREFIX = 'DEV.';

/**
 * Canonical map from device-type identifier to the name prefix prepended to a
 * generated device name (e.g. `3F COMP. ABC1D23`).
 *
 * Single source of truth, mirrored from
 * `data-ingestion-prod/packages/presetup-nextjs/src/lib/naming-rules.ts`
 * (`TYPE_PREFIX_MAP`). The `SW_*` board family (RFC-0003) is kept in sync with
 * that project's `structure-builder.ts`.
 */
export const DEVICE_TYPE_PREFIX_MAP: Record<string, string> = {
  COMPRESSOR: '3F COMP.',
  VENTILADOR: '3F VENT.',
  SELETOR_AUTO_MANUAL: 'S_AUTO_MANUAL.',
  TERMOSTATO: 'TEMP.',
  '3F_MEDIDOR': '3F',
  MOTOR: '3F MOTR.',
  ESCADA_ROLANTE: '3F ESRL.',
  ELEVADOR: '3F ELEV.',
  HIDROMETRO: 'HIDR.',
  SOLENOIDE: 'ABFE.',
  CONTROLE_REMOTO: 'AC',
  CAIXA_D_AGUA: 'SCD',
  CONTROLE_AUTOMACAO: 'GW_AUTO.',
  // RFC-0003 — SW_* board family (keep in sync with structure-builder.ts).
  SW_ILUMINACAO: 'ILUM.',
  SW_COMPRESSOR: 'COMP.',
  SW_GERADOR: 'GER.',
  SW_REDE: 'REDE',
};

/**
 * Returns the registered name prefix for a device type, or
 * `DEFAULT_DEVICE_TYPE_PREFIX` (`'DEV.'`) when the type is unknown/empty.
 *
 * Lookup is exact (keys are uppercase identifiers); pass the device's
 * canonical `type`/`deviceType` string.
 */
export function getDeviceTypePrefix(deviceType?: string | null): string {
  return DEVICE_TYPE_PREFIX_MAP[deviceType || ''] || DEFAULT_DEVICE_TYPE_PREFIX;
}
